version: '3.8'

services:
  db:
    restart: unless-stopped
    networks:
      - cookbook-network
    image: mysql:latest
    container_name: mysql-cookbook
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_SECRET}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - mysql-volume:/var/lib/mysql 

volumes:
  mysql-volume:
    name: cookbook-mysql

networks:
  cookbook-network:
    name: cookbook-network